BROKER: Logging
Mums-Who-Code/JustLearn.Services pull request #19
Opened 2021-11-12 00:08 UTC by Shrabanac

Closes #17

2021-11-12 04:23 UTC, NaynaMallick commented on JustLearn.Services.Api/Brokers/Loggings/LoggingBroker.cs
> +        public LoggingBroker(ILogger<LoggingBroker> logger)
add fat arrow here

2021-11-13 00:01 UTC, juturul commented on JustLearn.Services.Api/Brokers/Loggings/LoggingBroker.cs
> +            this.logger.LogWarning(message);
Add new line here

2021-11-13 00:07 UTC, juturul approved these changes

2021-11-13 05:32 UTC, NaynaMallick approved these changes

2021-11-14 19:37 UTC, ShriHumrudha requested changes

2021-11-14 19:37 UTC, ShriHumrudha commented on JustLearn.Services.Api/Brokers/Loggings/LoggingBroker.cs
> +using System;
Run code cleanup

2021-11-15 20:08 UTC, NaynaMallick approved these changes

2021-11-16 01:51 UTC, ShriHumrudha approved these changes

2021-11-16 02:02 UTC, merged