INFRA: Initialize Build Project
Mums-Who-Code/JustLearn.Services pull request #2
Opened 2021-11-02 02:03 UTC by Shrabanac

Closes #1

2021-11-02 16:55 UTC, ShriHumrudha requested changes

2021-11-02 16:55 UTC, ShriHumrudha commented on JustLearn.Services.Infrastructure.Build/Program.cs
> +using System.Collections.Generic;
run code cleanup

2021-11-03 01:21 UTC, NaynaMallick approved these changes

2021-11-03 01:25 UTC, juturul approved these changes

2021-11-03 01:58 UTC, ShriHumrudha approved these changes

2021-11-03 01:58 UTC, merged