DATA: Profile Model & Migration
Mums-Who-Code/JustLearn.Services pull request #31
Opened 2021-12-09 03:44 UTC by Shrabanac

Closes #30

2021-12-09 06:58 UTC, ShriHumrudha requested changes

2021-12-09 06:58 UTC, ShriHumrudha commented on JustLearn.Services.Api/Brokers/Storages/StorageBroker.Profile.cs
> +        DbSet<Profile> Profile { get; set; }
Table name should be plural - Profiles

2021-12-09 06:58 UTC, ShriHumrudha commented on JustLearn.Services.Api/Models/Profiles/Profile.cs
> +        public int Renewed { get; set; }
If you are thinking about count fo renewals then use the name 'RenewalCount'. The word 'Renewed' reads like - Renewed or Not.

2021-12-09 06:58 UTC, ShriHumrudha commented on JustLearn.Services.Api/Models/Profiles/ProfileStatus.cs
> +        ACTIVE,
Active,
Inactive

No need for all caps. Same for ProfileType.

2021-12-10 01:51 UTC, NaynaMallick approved these changes

2021-12-10 17:46 UTC, ShriHumrudha approved these changes

2021-12-10 21:37 UTC, merged