INFRA: Initialize Api Project
Mums-Who-Code/JustLearn.Services pull request #9
Opened 2021-11-09 21:24 UTC by Shrabanac

Closes #8

2021-11-09 22:40 UTC, ShriHumrudha requested changes

2021-11-09 22:40 UTC, ShriHumrudha commented on JustLearn.Services.Api/JustLearn.Services.Api.csproj
> +    <TargetFramework>net5.0</TargetFramework>
6.0

2021-11-09 22:40 UTC, ShriHumrudha commented on JustLearn.Services.Api/Startup.cs
> +using Microsoft.AspNetCore.Builder;
Copyrights header

2021-11-09 22:40 UTC, ShriHumrudha commented on JustLearn.Services.Api/Startup.cs
> +using System.Threading.Tasks;
Run Code Cleanup

2021-11-09 22:40 UTC, ShriHumrudha commented on JustLearn.Services.Api/Startup.cs
> +        // This method gets called by the runtime. Use this method to add services to the container.
remove commented code

2021-11-10 01:56 UTC, NaynaMallick approved these changes

2021-11-10 01:59 UTC, ShriHumrudha approved these changes

2021-11-10 01:59 UTC, merged